
-- +migrate Up
CREATE TABLE IF NOT EXISTS company (
    id  SERIAL PRIMARY KEY,
    nome    VARCHAR(100) NOT NULL,
    token   VARCHAR(100) NOT NULL,
    callback VARCHAR(300) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS company;
